'''
schema_inspector.inspect(...)
  -> prompt_builder.build(...)
  -> retry_handler.run(...)
      -> code_generator.generate(...)
      -> safety_checker.check(...)
      -> execution_backend.execute(...)
          -> sandbox_executor.execute(...) # subprocess backend

Goal: create script.py with the LLM-generated code, create _snapscript_paths.py with the input/output file paths,
then execute script.py in a secure sandbox environment (subprocess) with the input file, and get the output file generated by the script, 
finally validate the output file and return the execution result (success/failure, stdout, stderr, execution time, etc)

WorkFLow: 
1. create temporary workspace
2. copy input file to workspace with a temp name (ex: input.csv or input.xlsx)
3. create _snapscript_paths.py with the input/output file paths as variables
4. create script.py with the LLM-generated code
5. execute script.py in the workspace using subprocess, with a timeout from config
6. if execution fails (non-zero exit code or timeout), return ExecutionResult
7. if execution succeeds, validate the output file
8. if output file is valid, copy it back to the requested output path and return success ExecutionResult
'''

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import pandas as pd

from snapscript.config import AppConfig
from snapscript.core.models import ExecutionResult


SCRIPT_NAME = "script.py"

# the module name for snapscript to write the input/output paths into, 
#   so that the generated script.py can import and use these paths
PATHS_MODULE_NAME = "_snapscript_paths.py"


def execute(code: str, input_path: Path, output_path: Path) -> ExecutionResult:
    config = AppConfig()
    start_time = time.monotonic() # record the start time for execution time calculation

    # create a temporary workspace for the execution, all files will be created and executed in this workspace
    with tempfile.TemporaryDirectory(prefix="snapscript_") as workspace_name:
        workspace = Path(workspace_name)
        temp_input_path = workspace / f"input{Path(input_path).suffix}" # /workspace/input.csv
        temp_output_path = workspace / _temp_output_name(Path(output_path)) # /workspace/input.csv

        # copy the input file to the workspace with a temp name, so that the generated script can read from it
        shutil.copy2(input_path, temp_input_path)
        # write the _snapscript_paths.py module with the input/output paths
        _write_paths_module(workspace, temp_input_path, temp_output_path)
        # write the generated code to script.py in the workspace
        _write_script(workspace, code)

        # use local python subprocess to execute the script.py in the workspace, with a timeout from config
        result = _run_script(workspace, config, start_time)
        if not result.success:
            return result

        validation_error = _validate_output(temp_output_path)
        if validation_error is not None:
            return _failure_result(
                stderr=validation_error,
                exit_code=result.exit_code,
                stdout=result.stdout,
                duration=_duration(start_time),
            )

        requested_output_path = Path(output_path)
        requested_output_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(temp_output_path, requested_output_path)

        return ExecutionResult(
            success=True,
            stdout=result.stdout,
            stderr=result.stderr,
            output_files=[requested_output_path],
            execution_time_seconds=_duration(start_time),
            exit_code=result.exit_code,
        )


# determine the temp output file extension based on the user's request, .csv or .xlsx
def _temp_output_name(output_path: Path) -> str:
    suffix = output_path.suffix
    if suffix:
        return f"output{suffix}"
    return "output"


'''
generate the following variables in _snapscript_paths.py for the script.py to use:
INPUT_PATH = "/tmp/snapscript_abc123/input.csv"
OUTPUT_PATH = "/tmp/snapscript_abc123/output.csv"
'''
def _write_paths_module(workspace: Path, input_path: Path, output_path: Path) -> None:
    content = (
        f"INPUT_PATH = {json.dumps(str(input_path))}\n"
        f"OUTPUT_PATH = {json.dumps(str(output_path))}\n"
    )
    # write the _snapscript_paths.py module in the workspace
    (workspace / PATHS_MODULE_NAME).write_text(content, encoding="utf-8")


# write the generated code to script.py in the workspace
def _write_script(workspace: Path, code: str) -> None:
    (workspace / SCRIPT_NAME).write_text(code, encoding="utf-8")


# execute the script.py in the workspace using subprocess, with a timeout from config
def _run_script(workspace: Path, config: AppConfig, start_time: float) -> ExecutionResult:
    try:
        # python script.py
        completed = subprocess.run(
            [sys.executable, SCRIPT_NAME],
            cwd=workspace, # run in the temp workspace folder
            capture_output=True, # capture stdout and stderr
            text=True, # decode stdout and stderr as strings
            timeout=config.execution_timeout_seconds, # set timeout from config
            check=False, # if exit code != 0, do not raise exception, we will handle it ourselves
        )
    # if timeout occurs, return failure result with timeout message in stderr
    except subprocess.TimeoutExpired as exc:
        stdout = exc.stdout if isinstance(exc.stdout, str) else ""
        stderr = exc.stderr if isinstance(exc.stderr, str) else ""
        message = (f"Execution timed out after {config.execution_timeout_seconds} seconds")

        if stderr:
            message = f"{message}\n{stderr}"
        return _failure_result(
            stderr=message,
            exit_code=-1,
            stdout=stdout,
            duration=_duration(start_time),
        )

    # if execution fails (non-zero exit code), return failure result with stderr and stdout
    if completed.returncode != 0:
        return _failure_result(
            stderr=completed.stderr,
            exit_code=completed.returncode,
            stdout=completed.stdout,
            duration=_duration(start_time),
        )

    # if execution succeeds, return success result with stdout and stderr
    return ExecutionResult(
        success=True,
        stdout=completed.stdout,
        stderr=completed.stderr,
        execution_time_seconds=_duration(start_time),
        exit_code=completed.returncode,
    )


# None = valid output, string = validation error message
def _validate_output(output_path: Path) -> str | None:
    if not output_path.exists():
        return "Output file was not created"
    if output_path.stat().st_size == 0:
        return "Output is empty"

    try:
        if output_path.suffix.lower() in {".xlsx", ".xls"}:
            preview = pd.read_excel(output_path, nrows=1)
        else:
            preview = pd.read_csv(output_path, nrows=1)
    except Exception as exc:
        return f"Output unreadable: {exc}"

    if preview.empty:
        return "Output is empty"
    return None


# helper function to create a failure ExecutionResult
def _failure_result(stderr: str, exit_code: int, stdout: str, duration: float) -> ExecutionResult:
    return ExecutionResult(
        success=False,
        stdout=stdout,
        stderr=stderr,
        output_files=[],
        execution_time_seconds=duration,
        exit_code=exit_code,
    )


# calculate the duration of execution from the start time to now
def _duration(start_time: float) -> float:
    return time.monotonic() - start_time
