'''
schema_inspector.inspect(...)
  -> prompt_builder.build(...)
  -> retry_handler.run(...)
      -> code_generator.generate(...)
      -> safety_checker.check(...)
      -> execution_backend.execute(...)
          -> sandbox_executor.execute(...) # subprocess backend

Goal: create script.py with the LLM-generated code, create _snapscript_paths.py with the input/output file paths,
then execute script.py in a secure sandbox environment (subprocess) with the input file, and get the output file generated by the script, 
finally validate the output file and return the execution result (success/failure, stdout, stderr, execution time, etc)

WorkFLow: 
1. create temporary workspace
2. copy input file to workspace with a temp name (ex: input.csv or input.xlsx)
3. create _snapscript_paths.py with the input/output file paths as variables
4. create script.py with the LLM-generated code
5. execute script.py in the workspace using subprocess, with a timeout from config
6. if execution fails (non-zero exit code or timeout), return ExecutionResult
7. if execution succeeds, validate the output file
8. if output file is valid, copy it back to the requested output path and return success ExecutionResult
'''

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import pandas as pd

from snapscript.config import AppConfig
from snapscript.core.models import ExecutionResult, InputFileSpec


SCRIPT_NAME = "script.py"

# the module name for snapscript to write the input/output paths into, 
#   so that the generated script.py can import and use these paths
PATHS_MODULE_NAME = "_snapscript_paths.py"
SAFE_FILENAME_PATTERN = re.compile(r"[^A-Za-z0-9._-]+")


def execute(code: str, input_path: Path, output_path: Path) -> ExecutionResult:
    input_spec = InputFileSpec(name="input", path=Path(input_path))
    return _execute_with_inputs(code, [input_spec], Path(output_path), single_file=True)


def execute_many(
    code: str,
    inputs: list[InputFileSpec],
    output_path: Path,
) -> ExecutionResult:
    return _execute_with_inputs(code, inputs, Path(output_path), single_file=False)


def _execute_with_inputs(
    code: str,
    inputs: list[InputFileSpec],
    output_path: Path,
    single_file: bool,
) -> ExecutionResult:
    config = AppConfig()
    start_time = time.monotonic() # record the start time for execution time calculation

    # create a temporary workspace for the execution, all files will be created and executed in this workspace
    with tempfile.TemporaryDirectory(prefix="snapscript_") as workspace_name:
        workspace = Path(workspace_name)
        copied_inputs = _copy_inputs_to_workspace(inputs, workspace)
        temp_input_path = copied_inputs["input"] if single_file else None
        temp_output_path = workspace / _temp_output_name(output_path)

        # write the _snapscript_paths.py module with the input/output host temp paths
        _write_paths_module(workspace, temp_input_path, temp_output_path, copied_inputs)
        # write the generated code to script.py in the workspace
        _write_script(workspace, code)

        # use local python subprocess to execute the script.py in the workspace, with a timeout from config
        result = _run_script(workspace, config, start_time)
        if not result.success:
            return result

        validation_error = _validate_output(temp_output_path)
        if validation_error is not None:
            return _failure_result(
                stderr=validation_error,
                exit_code=result.exit_code,
                stdout=result.stdout,
                duration=_duration(start_time),
            )

        requested_output_path = output_path
        requested_output_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(temp_output_path, requested_output_path)

        return ExecutionResult(
            success=True,
            stdout=result.stdout,
            stderr=result.stderr,
            output_files=[requested_output_path],
            execution_time_seconds=_duration(start_time),
            exit_code=result.exit_code,
        )


# determine the temp output file extension based on the user's request, .csv or .xlsx
def _temp_output_name(output_path: Path) -> str:
    suffix = output_path.suffix
    if suffix:
        return f"output{suffix}"
    return "output"


'''
generate the following variables in _snapscript_paths.py for the script.py to use:
INPUT_PATH = "/tmp/snapscript_abc123/input.csv", host temp path
INPUT_PATHS = {"input": INPUT_PATH}
OUTPUT_PATH = "/tmp/snapscript_abc123/output.csv"
'''
def _write_paths_module(
    workspace: Path,
    input_path: Path | None,
    output_path: Path,
    input_paths: dict[str, Path],
) -> None:
    if input_path is None:
        input_path_content = "None"
        input_paths_content = json.dumps(
            {name: str(path) for name, path in input_paths.items()},
            sort_keys=True,
        )
    else:
        input_path_content = json.dumps(str(input_path))
        input_paths_content = '{"input": INPUT_PATH}'

    content = (
        f"INPUT_PATH = {input_path_content}\n"
        f"INPUT_PATHS = {input_paths_content}\n"
        f"OUTPUT_PATH = {json.dumps(str(output_path))}\n"
    )
    # write the _snapscript_paths.py module in the workspace
    (workspace / PATHS_MODULE_NAME).write_text(content, encoding="utf-8")


def _copy_inputs_to_workspace(
    inputs: list[InputFileSpec],
    workspace: Path,
) -> dict[str, Path]:
    copied_inputs: dict[str, Path] = {}
    for index, input_spec in enumerate(inputs):
        temp_input_path = workspace / _safe_input_filename(index, input_spec)
        shutil.copy2(input_spec.path, temp_input_path)
        copied_inputs[input_spec.name] = temp_input_path
    return copied_inputs


def _safe_input_filename(index: int, input_spec: InputFileSpec) -> str:
    source_name = Path(input_spec.display_filename or input_spec.path.name).name
    safe_source_name = SAFE_FILENAME_PATTERN.sub("_", source_name).strip("._")
    if not safe_source_name:
        safe_source_name = f"input{Path(input_spec.path).suffix}"
    safe_logical_name = SAFE_FILENAME_PATTERN.sub("_", input_spec.name).strip("._")
    return f"input_{index}_{safe_logical_name}_{safe_source_name}"


# write the generated code to script.py in the workspace
def _write_script(workspace: Path, code: str) -> None:
    (workspace / SCRIPT_NAME).write_text(code, encoding="utf-8")


# execute the script.py in the workspace using subprocess, with a timeout from config
def _run_script(workspace: Path, config: AppConfig, start_time: float) -> ExecutionResult:
    try:
        # python script.py
        completed = subprocess.run(
            [sys.executable, SCRIPT_NAME],
            cwd=workspace, # run in the temp workspace folder
            capture_output=True, # capture stdout and stderr
            text=True, # decode stdout and stderr as strings
            timeout=config.execution_timeout_seconds, # set timeout from config
            check=False, # if exit code != 0, do not raise exception, we will handle it ourselves
        )
    # if timeout occurs, return failure result with timeout message in stderr
    except subprocess.TimeoutExpired as exc:
        stdout = exc.stdout if isinstance(exc.stdout, str) else ""
        stderr = exc.stderr if isinstance(exc.stderr, str) else ""
        message = (f"Execution timed out after {config.execution_timeout_seconds} seconds")

        if stderr:
            message = f"{message}\n{stderr}"
        return _failure_result(
            stderr=message,
            exit_code=-1,
            stdout=stdout,
            duration=_duration(start_time),
        )

    # if execution fails (non-zero exit code), return failure result with stderr and stdout
    if completed.returncode != 0:
        return _failure_result(
            stderr=completed.stderr,
            exit_code=completed.returncode,
            stdout=completed.stdout,
            duration=_duration(start_time),
        )

    # if execution succeeds, return success result with stdout and stderr
    return ExecutionResult(
        success=True,
        stdout=completed.stdout,
        stderr=completed.stderr,
        execution_time_seconds=_duration(start_time),
        exit_code=completed.returncode,
    )


# None = valid output, string = validation error message
def _validate_output(output_path: Path) -> str | None:
    if not output_path.exists():
        return "Output file was not created"
    if output_path.stat().st_size == 0:
        return "Output is empty"

    try:
        if output_path.suffix.lower() in {".xlsx", ".xls"}:
            preview = pd.read_excel(output_path, nrows=1)
        else:
            preview = pd.read_csv(output_path, nrows=1)
    except Exception as exc:
        return f"Output unreadable: {exc}"

    if preview.empty:
        return "Output is empty"
    return None


# helper function to create a failure ExecutionResult
def _failure_result(stderr: str, exit_code: int, stdout: str, duration: float) -> ExecutionResult:
    return ExecutionResult(
        success=False,
        stdout=stdout,
        stderr=stderr,
        output_files=[],
        execution_time_seconds=duration,
        exit_code=exit_code,
    )


# calculate the duration of execution from the start time to now
def _duration(start_time: float) -> float:
    return time.monotonic() - start_time
